### ISSUE TITLE
Does debug visualization work?

### ISSUE THREAD

**Issue by goldingdamien** [serratus/quaggaJS#286]
I've tried an example with all the debug settings on, but I don't see any visualization.
The example below does have visualization but it uses a separate script. Why?

https://serratus.github.io/quaggaJS/examples/live_w_locator.html

https://github.com/serratus/quaggaJS/blob/eff0c5ad12b648e5ec938ce13b4cdc175effc5bb/example/live_w_locator.js

**Comment by radar1975** [comment]
Same issue ... here could someone help ?

**Comment by jonaaix** [comment]
I cloned the repository and extracted this code from the example to have visualization. The config debug parameters like `drawBoundingBox` do not work. Note that I converted the code to typescript.

```ts
Quagga.onProcessed(
    (result: {
    boxes: { filter: (arg0: (box: any) => boolean) => { forEach: (arg0: (box: any) => void) => void } };
    box: any;
    codeResult: { code: any };
    line: any;
    }) => {
    const drawingCtx = Quagga.canvas.ctx.overlay;
    const drawingCanvas = Quagga.canvas.dom.overlay;

    if (result) {
        if (result.boxes) {
            drawingCtx.clearRect(
                0,
                0,
                parseInt(drawingCanvas.getAttribute('width'), 10),
                parseInt(drawingCanvas.getAttribute('height'), 10)
            );
            result.boxes
                .filter(box => box !== result.box)
                .forEach(box => {
                Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, {
                    color: 'lightblue',
                    lineWidth: 3
                });
                });
        }

        if (result.box) {
            Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, {
                color: 'lightgreen',
                lineWidth: 3
            });
        }

        if (result.codeResult && result.codeResult.code) {
            Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, {
                color: 'red',
                lineWidth: 3
            });
        }
    }
    }
);
```

You may need some additional CSS to have the boxes as video overlay. `::ng-deep` is required for Angular apps, otherwise remove it.
```scss
#scanner-output {
   width: 100vw;
   height: 100vh;
   background: black;
   position: relative;
   display: flex;
   align-items: center;

   ::ng-deep {
      canvas,
      video {
         position: absolute;
         width: 100%;
         height: auto;
      }
   }
}
```
