### ISSUE TITLE
How to resize/make it responsive with css?

### ISSUE THREAD

**Issue by sam-lex** [serratus/quaggaJS#295]
I've follow this video tutorial: https://www.youtube.com/watch?v=qzbHxlQAa5o, but can't get the css to work.

*html:*
```html
<div id="barcode-scanner"></div>
```
*.ts*
```typescript
private _initQuagga() {
  Quagga.init({
    inputStream: {
      name: 'Live',
      type: 'LiveStream',
      target: document.querySelector('#barcode-scanner')
    },
    decoder: {
      readers: ['code_128_reader']
    }
  }, (err) => {
    if (err) {
      this.logger.error('Err. on initializing Quagga:', err);
      return;
    }
    this.logger.debug('Quagga initialized.');
  });
}
```
*.scss*
```scss
#barcode-scanner video, canvas {
  width: 100%;
  height: auto;
}

#barcode-scanner video.drawingBuffer, canvas.drawingBuffer {
  display: none;
}
```
The css just doesn't do anything on the video/canvas, even with `!important` it changes nothing.  
I also tried downgrading to 0.11.6 which is the same version as the video, but still can't get it to work.  
Setting the video's width from Chrome's inspector works perfectly though.

Btw, there's also a canvas floating to the right taking a massive blank space which can't be hidden with css, how to fix this?

More infos:
Angular: 5.2.0
quagga: 0.12.1

Thank you very much!
